Make IndentBlock work regardless of editor plugins order.
ckeditor/ckeditor5-indent pull request #20
Opened 2019-10-04 07:57 UTC by jodator

Checking schema for registered elements should be done
in afterInit call to prevent plugin ordering related bugs.

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Make IndentBlock work regardless of editor plugins order. Closes #19.

2019-10-07 14:32 UTC, Reinmar requested changes
The minimal amount of code should be moved to `afterInit()`. As much as possible should be done inside `init()` to make those things available to other plugins.

2019-10-09 09:41 UTC, jodator commented
I think that now it makes more sense.

2019-10-10 09:05 UTC, oleq commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
I was wondering since we're after the initialization phase, maybe we could figure out some better way to learn about model element names? For instance, the heading feature is [configurable](https://ckeditor.com/docs/ckeditor5/latest/api/module_heading_heading-HeadingConfig.html#member-options) and these may not be necessarily the true names of elements. 

Maybe we can fish them out of the heading config? No need to use `schema.isRegistered( elementName )` then.

2019-10-10 09:44 UTC, jodator commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
Well, we could but I don't know if this is worth the hassle:

```js
const knowElements = [ 
    'paragraph', // we must work withouth Heading feature
    ...( editor.config.get( 'heading.options' ) || [] )
        .map( option => option.model )
        .filter( name => name !== 'pargraph' ) /// and we don't want double entries
].forEach( name => schema.extend( name. { allowAttributes: 'blockIndent' } ) );
```

2019-10-10 09:45 UTC, jodator commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
For me both are equally fine.

2019-10-10 10:25 UTC, oleq commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
I think the following should do the trick

```js
new Set( [ 
	'paragraph',
	...editor.config.get( 'heading.options' ).map( ( { model } ) => model )
] ).forEach( name => schema.extend( name, { allowAttributes: 'blockIndent' } ) )
```

`Set` ensures unique values, and I guess some `heading.options` are always defined (`editor.config.define` in `HeadingEditing`).

2019-10-10 10:27 UTC, oleq commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
But this is not the scope of this PR I guess. I created a separate issue https://github.com/ckeditor/ckeditor5/issues/5565.

2019-10-10 10:38 UTC, merged

2019-10-10 10:40 UTC, jodator commented on src/indentblock.js
> +		const knownElements = [ 'paragraph', 'heading1', 'heading2', 'heading3', 'heading4', 'heading5', 'heading6' ];
OH, forgot about the `Set` :D Now it looks better and we could do that.